spring:
  application:
    name: API_CHAT

  data:
    mongodb:
      uri: mongodb://root:1134@localhost:27017/api_chat?authSource=admin
      auto-index-creation: true

minio:
  endpoint: http://localhost:9000
  access-key: admin
  secret-key: admin123
  bucket-name: images

resend:
  api-key: ${RESEND_API_KEY}
  from: ${DEFAULT_FROM_EMAIL}